server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  #配置开发模式 test--测试，dev--开发， prod--正式
  profiles:
    active: test,dev
  #配置redis
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379

#mybatisplus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cloud.spring.demo.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      db-type: postgre_sql
    #刷新mapper 调试神器
    refresh: true
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#设置debug=true，可以看SpringBoot帮我们做了哪些自动配置
debug: false

#quartz定时任务配置
quartz:
   schedule-name: QUARTZ_SCHEDULER
   thread-count: 10
   thread-name-prefix: quartz_worker
   tasks: ReportTimeTask:*/10 * * * * ? *

